name: Test and Build

on: [push, pull_request]

jobs:

  test-lib:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features --lib --manifest-path payjoin/Cargo.toml

  build-payjoin-client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cd payjoin-client
      - name: build payjoin example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path payjoin-client/Cargo.toml

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo clippy -- -D warnings
